version: '2.1'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - craft
    volumes_from:
      - craft
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf # nginx configuration (see below)
      - ./web/assets:/var/www/html/web/assets # For static assets (media, js and css).

  craft:
    image: urbantrout/craftcms:mysql # Use mysql instead of postgresql
    depends_on:
      - mariadb
    volumes:
      - ./web/assets:/var/www/html/web/assets:z
      - ./storage/backups:/var/www/html/storage/backups # Used for db restore on start.
      - ./templates:/var/www/html/templates # Craft CMS template files
      # - ./translations:/var/www/html/translations
      - ./config/redactor:/var/www/html/config/redactor
      - ./config/general.php:/var/www/html/config/general.php
      - ./config/imager.php:/var/www/html/config/imager.php
      - ./composer.json:/var/www/html/composer.json
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      # DEPENDENCIES: >- # additional composer packages
        
      CRAFTCMS_EMAIL: admin@company.com
      CRAFTCMS_USERNAME: SuperAdmin
      CRAFTCMS_PASSWORD: Pas5WordMetaCell
      CRAFTCMS_SITENAME: MetaCell
      CRAFTCMS_SITEURL: http://localhost # Optional

      # REDIS_HOST: redis
      # SESSION_DRIVER: redis
      # CACHE_DRIVER: redis

      DB_SERVER: mariadb
      DB_NAME: craft
      DB_USER: craft
      DB_PASSWORD: secret
      DB_DATABASE: craft
      DB_SCHEMA: public
      DB_DRIVER: mysql
      DB_PORT: 3306
      DB_TABLE_PREFIX: metac
      DEFAULT_SITE_URL: http://localhost

  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: craft
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: craft
    volumes:
      # Persistent data
      - dbdata:/var/lib/mysql

  # redis:
  #   image: redis:4-alpine
  #   volumes:
  #     - redisdata:/data

volumes:
  dbdata:
  redisdata: