email:
  fromEmail: ipetrov87@gmail.com
  fromName: Metacell
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  ac757e69-61e5-4446-a1c8-0a249fd73e3d:
    name: Common
siteGroups:
  d14c9dca-37c3-4439-9c6c-7cbbbb484c9e:
    name: Metacell
sites:
  5d321cb4-ef6f-4ec7-8ea5-edbb05b24c96:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Metacell
    primary: true
    siteGroup: d14c9dca-37c3-4439-9c6c-7cbbbb484c9e
    sortOrder: 1
system:
  edition: solo
  live: true
  name: Metacell
  schemaVersion: 3.1.23
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
