apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: craft
  labels:
    chart: k8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: craft
    spec:
      containers:
      - name: craft
        # securityContext:
        #   runAsUser: 82
        #   fsGroup: 82
        image:  r.cfcr.io/facundorodriguez/craft:{{CF_SHORT_REVISION}}
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              - "/bin/sh"
              - "-c"
              - >
                cp -r /tmp/default/. /var/www/html/;
                cp -r /tmp/html/web/assets/. /var/www/html/web/assers/;
                cp -r /tmp/html/storage/backups/. /var/www/html/storage/backups/;
                cp -r /tmp/html/templates /var/www/html/templates/;
                cp -r /tmp/html/config/refactor/. /var/www/html/config/refactor/;
                cp -r /tmp/html/config/. /var/www/html/config/;
                cp /tmp/html/composer.json /var/www/html/composer.json;
                cp /tmp/html/php.ini /var/www/html/php.ini;
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        # readinessProbe:
        #   tcpSocket:
        #     port: 9000
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 5
        volumeMounts:
        - name: nfs-volume
          mountPath: /var/www/html
        # volumeMounts:
        # - name: html
        #   mountPath: /var/www/html
      imagePullSecrets:
      - name: codefresh-generated-r.cfcr.io-facu-website
      # initContainers:
      # - name: config-data
      #   image: busybox
      #   command: ["cp","/tmp/html/*","-R", "/var/www/html/"]
      # volumes:
      # - name: html
      #   persistentVolumeClaim:
      #     claimName: html
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs