apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    chart: k8s
  name: db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     chart: k8s
#   name: html
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
# status: {}