apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    chart: k8s
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    chart: k8s
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: craft
  labels:
    chart: k8s
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: craft
  selector:
    app: craft